// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function TarifAkisiniCalistir(arg1:number,arg2:number,arg3:number,arg4:string,arg5:string,arg6:string):Promise<main.TarifAkisiDurumu>;

export function TarifleriGetir():Promise<Array<main.YemekTarifi>>;
