// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function SenaryoBaslat(arg1:number,arg2:string):Promise<main.SenaryoGuncellemesi>;

export function SenaryoCevapla(arg1:string,arg2:string,arg3:main.SenaryoCevabi):Promise<main.SenaryoGuncellemesi>;

export function SenaryoIptal(arg1:string):Promise<void>;

export function TarifleriGetir():Promise<Array<main.TarifOzeti>>;
