// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SenaryoBaslat(arg1, arg2) {
  return window['go']['main']['App']['SenaryoBaslat'](arg1, arg2);
}

export function SenaryoCevapla(arg1, arg2, arg3) {
  return window['go']['main']['App']['SenaryoCevapla'](arg1, arg2, arg3);
}

export function SenaryoIptal(arg1) {
  return window['go']['main']['App']['SenaryoIptal'](arg1);
}

export function TarifleriGetir() {
  return window['go']['main']['App']['TarifleriGetir']();
}
